### PR TITLE
authenticatorSelection and authenticatorAttachment properties name fix

### PR DESCRIPTION
**Pull request by Wesseldr**
Changed property _authenticatorSelectionCriteria_ into _authenticatorSelection_. Also fixed the property name of The w3c writes "authenticatorSelection, of type AuthenticatorSelectionCriteria". (https://www.w3.org/TR/webauthn/#dom-publickeycredentialcreationoptions-authenticatorselection)
_userVerification_ is now working, when set to "required" it enforces a PIN setup during attestation and  asks for a pin during assertion.
Changed "attachment" into authenticatorAttachment, is now also working for "platform" and "cross-platform" also tested and working now with both Solo & Yubi... well both devices are rejected when in platform mode and that is according to specs :-)
Unit tests updated as well

### CODE REVIEW

**Comment by Wesseldr** [comment]
Unit tests run fine local, travis erros look like it missing some env settings that are needed these days.

**Comment by davedoesdev** [comment]
Nice! Are we moving to @jedrivisser now?

**Comment by Wesseldr** [comment]
> Nice! Are we moving to @jedrivisser now?
For the time being it's one of the most up to date for now. I've also forked Adam's, and merged most of the PR's from here but not the Android patch from Jedri. Also I've included my own patches (my PR here) like the package update and the migration from istanbul into nyc etc.
However I hope when Adam is back from the summer holidays he can kick a view PR's into the main here :) then the spinoffs are no longer needed and we can all focus here to support this lib to become better.

**Comment by davedoesdev** [comment]
Nice! Are we moving to @jedrivisser now

**Comment by thgreasi** [comment]
Any updates on this?

**Comment by JamesCullum** [comment]
Moved to my fork for now, as the other forks don't provide an npm package.

**Pull request merged**
