### PR TITLE
Extension handling and type fixes

### PR DESCRIPTION
**Pull request by HSMDBC**
We faced an issue which was (probably) caused by a Windows update which automatically added an extension ("credProtect") during the registration process.

We were therefore unable to read the CredentialPublicKey because an error was thrown. The cause of the error lies in the cbor-x package, whose "decode" function can only decode ONE cbor value and throws an error if other unprocessed cbor values are detected in the buffer (= extensions).

This PullRequest fixes this problem, the CredentialPublicKey can now be read if there are extensions. In addition, extensions are now also processed and returned as cbor-decoded objects (array).

Furthermore, we have fixed the type definition. Two properties were incorrectly named and could not be used in a Typescript project

### CODE REVIEW

**Comment by JamesCullum** [comment]
Thanks for the PR! Can you add tests for those parts, so that coverage also doesn't decrease? 👍

**Comment by Hexagon** [comment]
Looks good! Another thing that could improve is to revert the files in /dist (main.js and main.cjs). That's made automatically by the build pipeline.

**Comment by HSMDBC** [comment]
I cleaned the dist directory. Sorry, I accidentally linked issues with my commits (I'm relatively new to GitHub)

**Comment by JamesCullum** [comment]
Thanks, dist is removed now - can you also take care of test coverage? As hundreds of projects rely on this library, we should make sure that everything keeps working in the future 👍

**Comment by HSMDBC** [comment]
> Thanks, dist is removed now - can you also take care of test coverage? As hundreds of projects rely on this library, we should make sure that everything keeps working in the future 👍

I'm working on it. It's a bit difficult to understand the test setup and the other non-extension code parts

**Comment by JamesCullum** [comment]
Deno test is still failing after a retry - do you need some help with the error you're receiving?

**Comment by HSMDBC** [comment]
@JamesCullum yes, please help! I don't know how to reproduce this error on my local system because the code tests (lib + dist) work. I've investigated the error and know what's (theoretically) going wrong, but it doesn't make sense to me. The added extension object is processed as a public key in the "fromCose". This can only happen if the AT flag is set but no COSE-Key/PublicKey exists in the attestationCredentialData. I thought that the COSE_key is mandatory/required in the attestationCredentialData

**Comment by Hexagon** [comment]
@HSMDBC It seems like the problem was internal in cbor-x@1.3.1, updating to 1.4.0 fixes the problem in Deno.

I've opened a pull request to your master branch, which should fix it in this PR if merged.

https://github.com/HSMDBC/fido2-lib/pull/2

Changes:
*   Revert package name to fido2-lib (was fork-fido2-lib)
*   Update various dependencies in both node and deno lockfile

**Comment by HSMDBC** [comment]
does the coverage have to be triggered manually?

**Comment by Hexagon** [comment]
Guess @JamesCullum has to trigger coverage manually (?), besides that - LGTM 👍

**Pull request merged**
