### PR TITLE
Fix/allow http localhost

### PR DESCRIPTION
**Pull request by Sambego**
### Changed
- Allow http requests when the origin is localhost. 

Browser allow the use of the web-authentication API on localhost using http. To keep it consistent this library should also allow the use of http when using localhost.

### CODE REVIEW

**Comment by KrishnaPG** [comment]
Can this be merged please? Facing the same problem.

**Comment by Zyclotrop-j** [comment]
👍

**Comment by jappyjan** [comment]
please merge

**Comment by JamesCullum** [comment]
Snippet I use to patch the library due to the inactivity of this ticket

```
if(hostname == "localhost" && !disableLocalhostPatching) {
	const packageList = require("./package.json");
	
	const utilsLocation = require.resolve("fido2-lib/lib/utils.js");
	if(packageList.dependencies["fido2-lib"] == "^2.1.1" && fs.statSync(utilsLocation).size == 7054) {
		// FIDO2-Lib does not natively support localhost and due to little maintenance this issue hasn't been fixed yet. See https://github.com/apowers313/fido2-lib/pull/19/files
		// To increase usability, this script automatically patches this library if you want to use localhost
		console.warn("Localhost was detected for FIDO2 library - patching fido2-lib now!");
		
		const oldContent = fs.readFileSync(utilsLocation, {encoding: "UTF-8"});
		fs.writeFileSync(utilsLocation, oldContent.replace('if (originUrl.protocol !== "https:") {', 'if (originUrl.protocol !== "https:" && originUrl.hostname !== "localhost") {'));
	}
}
```

**Comment by JamesCullum** [comment]
Merged here, which is also available on npm: https://github.com/JamesCullum/fido2-lib

It also extends the localhost whitelist to secure context ending with `.localhost`.

**Comment by JamesCullum** [comment]
Merged using the extended version https://github.com/webauthn-open-source/fido2-lib/commit/86f002fdfc2e47910a13480636f02b09b7dff43d

**Pull request closed without merging**
