### PR TITLE
Export types of missing MDS classes and functions

### PR DESCRIPTION
**Pull request by gaizeror**
main.d.ts missing MDS types, partially solves https://github.com/webauthn-open-source/fido2-lib/issues/136

### CODE REVIEW

**Comment by JamesCullum** [comment]
Thanks for the contribution, it's more than welcome!

Can we do without a new external dependency? We've been working on slowly reducing dependencies where possible, so adding one only for types might offer alternative solutions. If it's only about static type definition, what would be the impact to copy them over?

I think the original idea behind the typescript was to only add the types for the common APIs. You mentioned that it only partly solves your request - what else would we need? I think the current goal is not to strive for 100%, but make it a pleasing experience for typescript authors.

**Comment by JamesCullum** [comment]
Thanks for the great feedback! Do you know where the additional deno-lock-file comes from? This is where my confusion was probably coming from.

**Comment by gaizeror** [comment]
Actually I am not familiar with deno, all I know is that deno is deprecated.
I would consider converting / forking this repo to a TS project to serve both JS and TS projects.
As for the deno file, it was automatically generated somehow

> Thanks for the great feedback! Do you know where the additional deno-lock-file comes from? This is where my confusion was probably coming from.

**Comment by JamesCullum** [comment]
> all I know is that deno is deprecated

I'm not sure where you've got that from, but I wasn't able to find any sources supporting that. Let's focus on the PR then. I'll remove the Deno.lock changes and merge then, as the changes otherwise are useful additions - thanks!

**Comment by orgaizer** [comment]
> > all I know is that deno is deprecated
> 
> I'm not sure where you've got that from, but I wasn't able to find any sources supporting that. Let's focus on the PR then. I'll remove the Deno.lock changes and merge then, as the changes otherwise are useful additions - thanks!

Sorry, it's only [deno bundler that is deprecated](https://docs.deno.com/runtime/manual/tools/bundler#:~:text=deno%20bundle%20has%20been%20deprecated,deno_emit%2C%20esbuild%20or%20rollup%20instead.). Anyways I couldn't make the lib work with MDS v3 so far, I think it's not true that it supports MDS V3. Do you know if there is a guide/example for it?

**Comment by JamesCullum** [comment]
I've seen a few PRs and unit tests about it, so I'm confident it should work. My own projects didn't use it, so I'd recommend searching around in our Github repository and issues for people with a similiar challenge.

**Pull request merged**
