### PR TITLE
Feature/deno support

### LINKED ISSUE #79: Feature request: Support for Deno/ESM
Would be really nice if this lib supported Deno and moved away from CommonJS!

I'm experimenting on porting fido2-lib to a dual mode Node/Deno-lib on my own, and migrating everything to ES6 while at it. But I guess the changes are too big to "pull back" into this lib (?).

What need to be done/What I'm experimenting on:

*  Reduce usage on Node-specific stuff; Replace Buffer with ArrayBuffer, replace crypto with webcrypto/subtle where possible
*  Favor zero subdependency dependencies when available, bundle and modify them if dependencies depend on eachother
*  Favor dependencies that already support import/export module pattern.
*  Favor dependencies that support Deno and/or browser usage.
*  Pay attention to using one, and only one, implementation of each function. Also make sure that dependencies use the same implementations (base64 is a good example, i found at least 6 different implementations in fido2-lib plus it's dependencies)

Check out https://github.com/Hexagon/webauthn for ideas and inspiration, and please drop an issue of you find anything that doesn't look ok :)

---
Update 2022-04-25

#### Status of @hexagon/webauthn  - Dual platform - Deno first - Node built

[https://github.com/Hexagon/webauthn](@hexagon/webauthn) is pretty much in sync with fido2-lib now.

- All features are implemented
- All Node tests implemented
- Deno first approach, where dependencies are imported by Deno, and a platform independent bundle with zero dependencies is built (`dist/webauthn.js`). The bundle work in both Deno and Node, and it should technically work in browser too.
- Code style (lint) upgraded to current recommended standards
- Etc ...

#### Status of hexagon/fido2-lib fork , Dual platform - Node and Deno codebase

I've also submitted a pull request with a Node-first/Dual platform version of fido2-lib at PR https://github.com/webauthn-open-source/fido2-lib/pull/80

Two alternatives, both support both Deno _and_ Node :)

### PR DESCRIPTION
**Pull request by Hexagon**
## Overview

Closes #79, adds Deno support by adding build artifact `dist/main.js`. This bundle is built using Deno's dependencies, and will be usable with Deno, (theoretically) browser - and even Node. It is primarily intended for Deno though.

As `dist/` is gitignored, this module cannot be added to deno.land/x yet. 

However, Deno users can import the bundle by using (as an example) jsdelivr, like this:

```js
import { Fido2Lib } from "https://cdn.jsdelivr.net/npm/fido2-lib@3.0.1/dist/main.js";
```

Example import is included in README

### Added

- `import_map.json` - Import map used by Deno to test `lib/*` and build `dist/main.js`
- `import_map.test.json` - Import mao used by Deno to test distributable `dist/main,js`
- `deno.jsonc` - Deno configutation file
- `test/helpers/chai-deno-shim.js` - Simple shim which translates chai calls to Deno assert equivalents, to be able to use the exact same test cases for Node and Deno
- Added Deno build step to `workflows/test.yml`
- `deno-lock.json` dependency integrity lock for Deno
- New deno task `update-deps` which re-writes the deno-lock.json

### Changed

- Fixed minor bugs that only showed up on Deno tests
- Updated `README.md`. (Importing instructions + Encourage consumers to use Denos integrity checking)
- Renamed test step in workflow from test to test_node
- Added Deno environment, and `deno task build` to release step of `workflows/test.yml`
- Bumped version to 3.0.1
- All tests renamed from `<name>Test.js` to `<name>.test.js`, as test names isn't configurable in Deno. Does still work in node of course.
- Make `deno task build` (and test) use lock file for integrity checking dependencies

### Removed

- One occurence of console.log

### CODE REVIEW

**Comment by Hexagon** [comment]
Ready for review

**Comment by JamesCullum** [comment]
`As dist/ is gitignored, this module cannot be added to deno.land/x yet.`

You mean in this repository or the projects that people use?
I would prefer it if people can just use the library directly and correctly.

**Comment by Hexagon** [comment]
I'll add a minor asap.

Deno users can choose freely where to import from, npm will be a good "source" for now. 

But in the long run, we should consider to add it to Deno.land/x, which in turns require the distributables to be available directly in the repo. See this for a similar "issue" https://github.com/openpgpjs/openpgpjs/issues/1504 .

Having the distributables in the repo also make more cdn services work ootb.

**Comment by JamesCullum** [comment]
I think my concern is less about including it via NPM, but that delivery is never directly via NPM but via another CDN. As packages usually don't validate the integrity properly, this feels like it'd be not secure enough. If we put it as part of the repository, it can be directly retrieved from the source and there is no CDN etc in between that can be manipulated.

I would like it that we can provide it directly from the repository. The solution with the gitignore of the dist folder will not work, as this way it is not automatically built, but needs to be built by the user and committed, right? 

What do you think of my proposal: As part of the publish step in Github, we can build and publish the deno version as a release in Github.

Github also has a [native package manager](https://github.com/features/packages) - we could also use it to upload the deno version.

What do you prefer?

**Comment by Hexagon** [comment]
Will have a look at the details and get back asap. Deno has built in sri and File locking mechanisms, need to explore this a bit deeper too.

**Comment by Hexagon** [comment]
First things first :)

Now we use dependency locking internally. I also added a notice in the readme, encouraging consumers to utilize Denos integrity checking features. As it is not mandatory yet (might be from 2.0).

Will continue thinking about how consumers best access the distributable.

**Comment by JamesCullum** [comment]
Great, let me know what direction you want to go - I can help with that as well!

Should we merge this one already, so that we can try building pipelines and making things accessible later?

**Comment by Hexagon** [comment]
Yeah, I think it would be ok to launch as it is now, leaving it to the consumer to determine what's trusted or not, and let them choose from one of the cdns pulling files from npm, (like jsdelivr on unpkg). We also encourage to use Deno's integrity checking features.

As you say we can continue to elaborate on a better/safer/cleaner distribution methods later 👍

**Comment by JamesCullum** [comment]
Great, thanks!

I noticed that the release workflow runs tests twice and appears [to throw quite a few warnings](https://github.com/webauthn-open-source/fido2-lib/runs/6413218672?check_suite_focus=true#step:7:1166) when building the bundle. Is this something that you can quickly fix?

**Comment by Hexagon** [comment]
Nice!

The tests running twice is actually intended. This is what's happening:

Node:

    Test against files in **lib**/main.js (entrypoint for ESM-usage)
    Build dist/main.cjs and commonjs-version of all tests
    Run cjs tests against **dist**/main.cjs (entrypoint for commonjs-usage)

Deno:

   Test against **lib**/main.js (Just as a sanity check)
   Build dist/main.js (entrypoint for Deno ESM usage)
   Test against **dist**/main.js

Will have a look at the warnings

**Pull request merged**
