### PR TITLE
Various fixes -> 3.1.4

### LINKED ISSUE #86: Cannot upgrade pkijs past 2.1.60
Cannot figure this one out...

All is ok with pkijs@2.1.60 - Error with pkijs@2.1.61

```bash
    verifyCertChain ...
      rejects on empty arguments ... ok (13ms)
      works for MDS2 ... FAILED (93ms)
        Error: No revocation values found for one of certificates: No valid CRLs found
                                throw new Error(res.resultMessage);
                                      ^
            at Function.verifyCertChain (/fido2-lib/lib/certUtils.js:587:10)
```
Failing test: 
https://github.com/webauthn-open-source/fido2-lib/blob/e60117e18244c4cf9420d026b957a55d17e71d5a/test/certUtils.test.js#L531

Related certs available here:
https://github.com/webauthn-open-source/fido2-lib/blob/e60117e18244c4cf9420d026b957a55d17e71d5a/test/helpers/fido2-helpers.js#L4598

Failing line:
https://github.com/webauthn-open-source/fido2-lib/blob/e60117e18244c4cf9420d026b957a55d17e71d5a/lib/certUtils.js#L587

Could it be related to this change in CertificateChainValidationEngine.js? Or something else?

image

### PR DESCRIPTION
**Pull request by Hexagon**
## Changelog

- Bump to 3.1.4

### Dependencies

- Update sinon 13 > 14
- Update tldts 5.7.77 -> 5.7.78
- Update asn1js 3.0.1 -> 3.0.2
- Update pkijs 2.1.60 -> 2.3.1 (Fixes #86)
- Update jose 4.7 -> 4.8.1
- Update @peculiar/webcrypto 1.3 -> 1.4
- Replace nyc (does not work with ESM) with c8, revives coverage on `npm test`, and should revive codecov

### Documentation

- Add short contribution guide to README.md
- Update example README.md jsdelivr -> deno.land/x

### Release process

- Remove dist.cjs from git auto commit in test.yml - dist.cjs is only ever needed by npm as it relies on unbundled npm dependencies.

### Fixed tests

- Always return promise in tests when using assert.isRejected, to avoid false positives
- Skip MDS2-tests in certUtils.test.js
- Modify rest of MDS2-cert-validation-tests to expect failure instead of success

### CODE REVIEW

**Comment by Hexagon** [comment]
Done!

**Comment by JamesCullum** [comment]
We should also think about how we can have the README contain the current version, so we don't forget it.
As the build pipeline is automated, this should happen automatically as well.

I'm not sure if we really need the import example twice - we can just have a short hint to use the import above, and link to that section with a jumpmark.

Whats the issue with publishing the updated main.cjs file as well - it wouldnt harm, would it? If anyone wants to use it, this way they can.

Also please don't commit a main.js - this is built by the pipeline automatically. Not sure if we need a pipeline to enforce that.

**Comment by Hexagon** [comment]
👍 Will have a look at this tonight

**Comment by Hexagon** [comment]
Not a final solution, but as a temporary fix readme now points to https://deno.land/x/fido2/dist/main.js , which will redirect to the latest version. Also added a note reminding to always use a fixed version.

I moved installation down just above examples, and "bundled" installation with import, this took away the need to split deno in installation/import.

I have no problem leaving .cjs it in dist, i might have been a case of over-optimization 😅 

Oh, removed main.js from commit and force pushed.

Btw... It's totally ok if you change my texts/comments etc after pulling. I do not speak english, and am struggling with the grammar 😄

**Comment by JamesCullum** [comment]
No worries, you're doing an amazing job - english isnt my native language either! Thanks a lot also for this commit.

Just one thing that currently isn't optimal with Deno, is that it often has 500 errors when downloading dependencies, and sometimes some of the tests fail due to what feels like a race condition in the deno tests. Usually re-running the pipeline works - not sure if there is a good solution in the deno universe for that. Otherwise I might add a pipeline step that reruns failed tasks automatically 👍

**Comment by Hexagon** [comment]
I've also noticed the race condition error a couple of times, but it has been a while now. I'll keep my eye open and see what can be done about it, if it happens again.

Don't know whats up with the dependency download though, nothing I've encountered. drop a line (and log) next time it happens, and I'll have a look 👍

**Pull request merged**
