### PR TITLE
Prevent package-lock.json creation

### PR DESCRIPTION
**Pull request by thgreasi**
Since the package-lock.json is never part of the published package, having it in the repo makes the CI tests to be run with different versions of the dependencies than the ones a fresh install by a user would fetch. As a result the CI will never surface regressions that might have been caused in the latest version of our dependencies and we will not realize that fresh install might have broke b/c of that.

### CODE REVIEW

**Comment by thgreasi** [comment]
Also resolves #54

**Comment by JamesCullum** [comment]
Official guideline is that the file should be committed and versioned as well: https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by thgreasi** [comment]
That's great for projects but not for libraries though, since it can conceal fresh install issues.
See: https://travis-ci.org/github/webauthn-open-source/fido2-lib/builds/746568155

**Comment by JamesCullum** [comment]
The issue was caused by the lockfile changing format, so older node versions removed 2 required packages during `npm prune`. Fixed it.

**Comment by thgreasi** [comment]
Regardless of the above issue, I still strongly feel that having a lock file in a library is wrong, simply because the ci is no longer testing reality.

I'm not going to start a debate though and respect your decision but let me add some references:
https://dev.to/gajus/stop-using-package-lock-json-or-yarn-lock-3ddi
https://jbeckwith.com/2019/12/18/package-lock/
https://www.twilio.com/blog/lockfiles-nodejs

**Pull request closed without merging**
