### PR TITLE
Support rpId same-origin relaxation

### LINKED ISSUE #21: rpIdHash validation incorrectly requires rpId to exactly match origin domain
I believe the webauthn spec allows rpId to be a registrable suffix of the origin domain, but https://github.com/apowers313/fido2-lib/blob/master/lib/validator.js#L365 only allows it to be exactly equal to the client origin domain.

Maybe Fido2Lib options.rpId should be used here, and `rsl` might need to be checked to verify that options.rpId is a registrable suffix of clientDataJSON.origin.

### PR DESCRIPTION
**Pull request by thgreasi**
Rebases and improves @reardencode 's #22
Resolves #21

Since this actually stops supporting the `origin` property that is atm used, it actually needs a major release.
Let me know if you prefer me to compatibility layer to support the old `origin` property as well and just mark it as deprecated.

Marked as draft just b/c I didn't have the time to test it on an actual server and just relied on the test cases.

### CODE REVIEW

**Comment by thgreasi** [comment]
Tests are failing b/c of #54 but are fixed with #53

**Comment by JamesCullum** [comment]
Can you make this a non-breaking change by adding an option between both?
This way, legacy code can keep on using origin and new ones can use rpId.
The code is similar enough that this should be the easier way.

**Comment by thgreasi** [comment]
Will do :+1:

**Comment by thgreasi** [comment]
@JamesCullum updated to also work with the now deprecated `origin` option so that this isn't a breaking change.
Let me know if you are fine with it, so that I can squash the commits a bit.

**Comment by JamesCullum** [comment]
I would remove the deprecated syntax from the README. 

Can you please make sure that the coverage does not decrease, so all new things are tested? 

In the same direction, please keep both the origin tests and just add the rpId ones, so that we catch both.

**Comment by thgreasi** [comment]
I gave this some extra thought and think that the approach followed by #22 might not be correct.
I'm now leaning towards, passing the origin of the request to be checked against the one included in the clientData and use the `rpId` as defined in the `Fido2Lib` instance.

**Comment by julienwoll** [comment]
Hello All, 

Thank you very much for that PR. I was about to report the exact same issue. The fact that the relaxation was not supported, which prevents using a key over different sub domains. But also, the fact that the function validateRpIdHash was comparing 2 pieces of data coming from the client side was bugging me a bit. Indeed, I would expect that we verify that the rpId sent by the key is equal to a value I expect as the relying party (as mentioned in the paragraph 7.1 step 89 of the spec): 

`Verify that the rpIdHash in authData is the SHA-256 hash of the RP ID expected by the Relying Party.`

Any idea on when this is going to be releases in the next version ? 

Thanks a lot for your help and this great lib.

**Comment by JamesCullum** [comment]
Hey @julienwoll once the PR has been finalized, it will be reviewed and be made available to use (see README for current way to get npm updates). As this is worked on by @thgreasi I believe the better question is "When will the PR be finalized" - what do you think @thgreasi ?

**Comment by thgreasi** [comment]
I'm only working on this a few hours during weekends but this weekend is kind of pressed.
As I mentioned earlier, after finishing the rebase of the original PR, fixing some edge cases & writing more tests, I want to take a step back to rethink the reasoning of the approach of the new argument.
@julienwoll that's exactly what I was thinking about.
I hope to have this merged during my EOY leave.

**Review by vigan-abd — COMMENTED** [review]
Hi guys, what's the status on this one? this PR seems to improve the lib, can you please merge it?

**Comment by thgreasi** [comment]
@vigan-abd I'm not sure this is following the correct approach. Did you have the chance to test it?

**Comment by JamesCullum** [comment]
Merged from @vigan-abd in https://github.com/FIDO-Tools/fido2-library/pull/14

**Comment by Mohana-Manikandan** [comment]
Hi. Is this PR merged or abandoned ?

**Pull request closed without merging**
