### PR TITLE
Validator for extensions

### PR DESCRIPTION
**Pull request by HSMDBC**
Fixed error: "internal audit failed: webAuthnExtensions was not validated"

Added missing validator for auditing extension.

### CODE REVIEW

**Comment by HSMDBC** [comment]
Can you tell me why this pull request lists the "old commits" that were already merged by the previous pull request?

**Comment by Hexagon** [comment]
Not sure, but the simplest way to get a clean PR is to sync "your" master with webauthn-open-source/fido2-lib, create a new branch (per PR) and work in that branch. Never commit to master, just keep it in sync with webauthn-open-source/fido2-lib, and use that as a base for your feature branches.

**Comment by HSMDBC** [comment]
@Hexagon thanks, i will give it a try next time. (btw, I've synced the master. But it really doesn't seem like a good idea to commit directly to the master)

**Comment by HSMDBC** [comment]
@JamesCullum can you check that please?

**Comment by Hexagon** [comment]
LGTM, original post by Codecov is updated with a positive result.

**Comment by JamesCullum** [comment]
Thanks a lot for the great PR, quick fix, good test coverage

Hexagon already merged, so I will close here

**Pull request merged**
