### PR TITLE
feat: supporting android and ios rp origins

### PR DESCRIPTION
**Pull request by TomerDavid-Transmit**
While using the lib, I noticed that the `rpOrigin`, as returned by the android native fido2 client attestation response, is considered invalid. 
Made this change for the lib to support android FacetIDs as origins.
In depth explanation: https://fidoalliance.org/specs/uaf-v1.0-id-20141122/fido-appid-and-facets-v1.0-id-20141122.html#the-appid-and-facetid-assertions
Also added support for the iOS FacetID prefix, as specified in the fido2 docs above.
Empirically, our experiments with native iOS clients resulted with `https` rp origins - so the docs might be outdated, but I added the FacetID support just in case.

### CODE REVIEW

**Comment by TomerDavid-Transmit** [comment]
> Hey @TomerDavid-Transmit thanks for the contribution! Are you trying to achieve the same thing as in #122 ?

@JamesCullum yes, except for the prefix I think we should look for. #122 searches `android:` and `ios:` as prefixes, and I think we should search for `android:apk-key-hash:` and `ios:bundle-id:` for specificity.
was just working on adding the iOS support + tests to this PR

**Comment by Rimmassukhovsky** [comment]
Very much needed addition!

**Comment by RonGoldzimer** [comment]
Finally!

**Review by gaizeror — APPROVED** [review]
Thanks for this contribution, was waiting for it for a long time!

**Comment by HananArgov** [comment]
looks like an encompassing code.
good one :)

**Comment by Hexagon** [comment]
LGTM 👍  This one is slightly more complete than #121

**Review by Hexagon — APPROVED** [review]

**Comment by amoskle** [comment]
Nice change!

**Comment by JamesCullum** [comment]
@Hexagon I think 3.4.0 would make more sense as new feature, as previously we didn't support it.

Will merge and do it - thanks!

**Pull request merged**
