### PR TITLE
Packed self attestation

### PR DESCRIPTION
**Pull request by agmcleod**
Addresses: #31 

Based this off of implementation in https://github.com/strangerlabs/webauthn, as well as what's defined in the webauthn spec. https://w3c.github.io/webauthn/#sctn-packed-attestation

I am not a security expert, so definitely have a look over it to be sure I didn't overlook something

### CODE REVIEW

**Comment by JamesCullum** [comment]
Thanks a lot for the PR - let me know once you think it's ready to review

**Comment by agmcleod** [comment]
@JamesCullum Can take a look when you get a chance. Added tests

**Comment by JamesCullum** [comment]
Thanks a lot - code looks great! Now only the test coverage is not exactly where we would like to have it - you are checking a lot of good components, but it looks like there is not really an end-to-end test that checks exactly the methods you are offering to the developer.

You can see the details here: https://app.codecov.io/gh/webauthn-open-source/fido2-lib/compare/72/changes#D1L231

Can you improve the coverage at least for those two added functions?

**Comment by agmcleod** [comment]
@JamesCullum added a test, and was able to get the coverage up over 80.

**Comment by JamesCullum** [comment]
Great quality, awesome work and very fast - your contribution is highly appreciated! Do you want to do the honors to bump the version in package.json to the next minor update, so that on the merge is gets automatically published on npm? 👍

**Comment by agmcleod** [comment]
@JamesCullum done, bumped to 2.7.0 from 2.6.8

**Comment by JamesCullum** [comment]
Great, thanks a lot - suite ran through and package is published 👍

**Pull request merged**
